--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: games; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.games (
    id integer NOT NULL,
    leagueid integer NOT NULL,
    hometeamid integer NOT NULL,
    awayteamid integer NOT NULL,
    date text NOT NULL,
    name text NOT NULL,
    hometeamscore integer NOT NULL,
    hometeamassists integer NOT NULL,
    hometeamthrees integer NOT NULL,
    hometeamsteals integer NOT NULL,
    hometeamblocks integer NOT NULL,
    awayteamscore integer NOT NULL,
    awayteamassists integer NOT NULL,
    awayteamthrees integer NOT NULL,
    awayteamsteals integer NOT NULL,
    awayteamblocks integer NOT NULL
);


ALTER TABLE public.games OWNER TO postgres;

--
-- Name: games_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.games ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.games_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: knex_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.knex_migrations (
    id integer NOT NULL,
    name character varying(255),
    batch integer,
    migration_time timestamp with time zone
);


ALTER TABLE public.knex_migrations OWNER TO postgres;

--
-- Name: knex_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.knex_migrations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.knex_migrations_id_seq OWNER TO postgres;

--
-- Name: knex_migrations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.knex_migrations_id_seq OWNED BY public.knex_migrations.id;


--
-- Name: knex_migrations_lock; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.knex_migrations_lock (
    index integer NOT NULL,
    is_locked integer
);


ALTER TABLE public.knex_migrations_lock OWNER TO postgres;

--
-- Name: knex_migrations_lock_index_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.knex_migrations_lock_index_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.knex_migrations_lock_index_seq OWNER TO postgres;

--
-- Name: knex_migrations_lock_index_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.knex_migrations_lock_index_seq OWNED BY public.knex_migrations_lock.index;


--
-- Name: leagues; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.leagues (
    id integer NOT NULL,
    name text NOT NULL
);


ALTER TABLE public.leagues OWNER TO postgres;

--
-- Name: leagues_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.leagues ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leagues_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: players; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.players (
    id integer NOT NULL,
    leagueid integer NOT NULL,
    teamid integer NOT NULL,
    role text NOT NULL,
    city text NOT NULL,
    phone text NOT NULL,
    name text NOT NULL
);


ALTER TABLE public.players OWNER TO postgres;

--
-- Name: players_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.players ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.players_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schemaversion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.schemaversion (
    version bigint NOT NULL,
    name text,
    md5 text,
    run_at timestamp with time zone
);


ALTER TABLE public.schemaversion OWNER TO postgres;

--
-- Name: teams; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.teams (
    id integer NOT NULL,
    leagueid integer NOT NULL,
    name text NOT NULL
);


ALTER TABLE public.teams OWNER TO postgres;

--
-- Name: teams_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.teams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teams_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: knex_migrations id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.knex_migrations ALTER COLUMN id SET DEFAULT nextval('public.knex_migrations_id_seq'::regclass);


--
-- Name: knex_migrations_lock index; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.knex_migrations_lock ALTER COLUMN index SET DEFAULT nextval('public.knex_migrations_lock_index_seq'::regclass);


--
-- Data for Name: games; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO leagues (name)
VALUES
    ('Tater Tots (8-10)'),
    ('Flyers (11-12)'),
    ('Trappers (13-15)'),
    ('Killas (16-18)');

INSERT INTO teams (leagueId, name)
VALUES
    (1, 'Supers'),
    (1, 'Importants'),
    (1, 'Spangleys'),
    (1, 'Terrors'),
    (2, 'Mirrors'),
    (2, 'Tables'),
    (2, 'Times'),
    (2, 'Kitties'),
    (3, 'Bobs'),
    (3, 'Sleeves'),
    (3, 'Bears'),
    (3, 'Bad Boys'),
    (4, 'Trippys'),
    (4, 'Snows'),
    (4, 'Buyers'),
    (4, 'Consumers');

INSERT INTO games (leagueId,homeTeamId,awayTeamId,date,name,homeTeamScore,homeTeamAssists,homeTeamThrees,homeTeamSteals,homeTeamBlocks,awayTeamScore,awayTeamAssists,awayTeamThrees,awayTeamSteals,awayTeamBlocks)
VALUES
    (1,1,2,'1/1','Game 1',0,0,0,0,0,0,0,0,0,0),
    (1,3,4,'1/1','Game 1',0,0,0,0,0,0,0,0,0,0),
    (1,1,3,'1/2','Game 2',0,0,0,0,0,0,0,0,0,0),
    (1,2,4,'1/2','Game 2',0,0,0,0,0,0,0,0,0,0),
    (1,4,1,'1/3','Game 3',0,0,0,0,0,0,0,0,0,0),
    (1,3,2,'1/3','Game 3',0,0,0,0,0,0,0,0,0,0),
    (1,2,1,'1/4','Game 4',0,0,0,0,0,0,0,0,0,0),
    (1,4,3,'1/4','Game 4',0,0,0,0,0,0,0,0,0,0),
    (2,5,6,'1/1','Game 1',0,0,0,0,0,0,0,0,0,0),
    (2,7,8,'1/1','Game 1',0,0,0,0,0,0,0,0,0,0),
    (2,5,7,'1/2','Game 2',0,0,0,0,0,0,0,0,0,0),
    (2,6,8,'1/2','Game 2',0,0,0,0,0,0,0,0,0,0),
    (2,8,5,'1/3','Game 3',0,0,0,0,0,0,0,0,0,0),
    (2,7,6,'1/3','Game 3',0,0,0,0,0,0,0,0,0,0),
    (2,6,5,'1/4','Game 4',0,0,0,0,0,0,0,0,0,0),
    (2,8,7,'1/4','Game 4',0,0,0,0,0,0,0,0,0,0),
    (3,9,10,'1/1','Game 1',0,0,0,0,0,0,0,0,0,0),
    (3,11,12,'1/1','Game 1',0,0,0,0,0,0,0,0,0,0),
    (3,9,11,'1/2','Game 2',0,0,0,0,0,0,0,0,0,0),
    (3,10,12,'1/2','Game 2',0,0,0,0,0,0,0,0,0,0),
    (3,12,9,'1/3','Game 3',0,0,0,0,0,0,0,0,0,0),
    (3,11,10,'1/3','Game 3',0,0,0,0,0,0,0,0,0,0),
    (3,10,9,'1/4','Game 4',0,0,0,0,0,0,0,0,0,0),
    (3,12,11,'1/4','Game 4',0,0,0,0,0,0,0,0,0,0),
    (4,13,14,'1/1','Game 1',0,0,0,0,0,0,0,0,0,0),
    (4,15,16,'1/1','Game 1',0,0,0,0,0,0,0,0,0,0),
    (4,13,15,'1/2','Game 2',0,0,0,0,0,0,0,0,0,0),
    (4,14,16,'1/2','Game 2',0,0,0,0,0,0,0,0,0,0),
    (4,16,13,'1/3','Game 3',0,0,0,0,0,0,0,0,0,0),
    (4,15,14,'1/3','Game 3',0,0,0,0,0,0,0,0,0,0),
    (4,14,13,'1/4','Game 4',0,0,0,0,0,0,0,0,0,0),
    (4,16,15,'1/4','Game 4',0,0,0,0,0,0,0,0,0,0);

INSERT INTO players (leagueId, teamId, role, city, phone, name)
VALUES
    (1, 1, 'Player', 'Bellevue', '(298)234-4897', 'Jimmy Taylor'),
    (1, 1, 'Player', 'Redmond', '(298)234-2397', 'Tim Donald'),
    (1, 1, 'Player', 'Auburn', '(298)634-4897', 'Brandon Filmore'),
    (1, 1, 'Player', 'Bellevue', '(292)234-4897', 'Carl Lozenge'),
    (1, 1, 'Player', 'Bellevue', '(298)234-4494', 'Tommy Table'),
    (1, 1, 'Coach', 'Bellevue', '(298)662-4897', 'Jim Varmand'),
    (1, 2, 'Player', 'Bellevue', '(298)234-4897', 'John Taylor'),
    (1, 2, 'Player', 'Redmond', '(298)234-4397', 'Timmy Donald'),
    (1, 2, 'Player', 'Auburn', '(298)634-4897', 'Brandino Filmore'),
    (1, 2, 'Player', 'Bellevue', '(292)334-4897', 'Carlos Lozenge'),
    (1, 2, 'Player', 'Kent', '(298)234-4434', 'Tommy Tom Table'),
    (1, 2, 'Coach', 'Issaquah', '(298)662-4897', 'Jimmy R. Vamanos'),
    (1, 3, 'Player', 'Bellevue', '(298)237-4897', 'Johnny Taylor'),
    (1, 3, 'Player', 'Kirkland', '(298)232-4397', 'Kimmy Donald'),
    (1, 3, 'Player', 'Auburn', '(298)634-5897', 'Trent Filmore'),
    (1, 3, 'Player', 'Bellevue', '(292)233-4897', 'Farla Lozenge'),
    (1, 3, 'Player', 'Tacoma', '(298)234-3494', 'Mickey Table'),
    (1, 3, 'Coach', 'Bellevue', '(298)669-4897', 'Terrell Varmand'),
    (1, 4, 'Player', 'Seattle', '(298)234-4597', 'Sammy Taylor'),
    (1, 4, 'Player', 'Redmond', '(298)264-4697', 'Lorenzo Donald'),
    (1, 4, 'Player', 'Auburn', '(298)434-4897', 'Fatima Filmore'),
    (1, 4, 'Player', 'Kimberly', '(291)234-4897', 'Aaron Lozenge'),
    (1, 4, 'Player', 'Everett', '(298)234-8794', 'Kevin Table'),
    (1, 4, 'Coach', 'Bellevue', '(298)662-2397', 'Jorge Varmand'),
    (2, 5, 'Player', 'Bellevue', '(298)234-4897', 'Jimmy Taylor'),
    (2, 5, 'Player', 'Redmond', '(298)234-4397', 'Tim Donald'),
    (2, 5, 'Player', 'Auburn', '(298)634-4897', 'Brandon Filmore'),
    (2, 5, 'Player', 'Bellevue', '(292)234-4897', 'Carl Lozenge'),
    (2, 5, 'Player', 'Bellevue', '(298)234-4494', 'Tommy Table'),
    (2, 5, 'Coach', 'Bellevue', '(298)662-4897', 'Jim Varmand'),
    (2, 6, 'Player', 'Bellevue', '(298)234-4897', 'John Taylor'),
    (2, 6, 'Player', 'Redmond', '(298)234-4397', 'Timmy Donald'),
    (2, 6, 'Player', 'Auburn', '(298)634-4897', 'Brandino Filmore'),
    (2, 6, 'Player', 'Bellevue', '(292)334-4897', 'Carlos Lozenge'),
    (2, 6, 'Player', 'Kent', '(298)234-4434', 'Tommy Tom Table'),
    (2, 6, 'Coach', 'Issaquah', '(298)662-4897', 'Jimmy R. Vamanos'),
    (2, 7, 'Player', 'Bellevue', '(298)237-4897', 'Johnny Taylor'),
    (2, 7, 'Player', 'Kirkland', '(298)232-4397', 'Kimmy Donald'),
    (2, 7, 'Player', 'Auburn', '(298)634-5897', 'Trent Filmore'),
    (2, 7, 'Player', 'Bellevue', '(292)233-4897', 'FArla Lozenge'),
    (2, 7, 'Player', 'Tacoma', '(298)234-3494', 'Mickey Table'),
    (2, 7, 'Coach', 'Bellevue', '(298)669-4897', 'Terrell Varmand'),
    (2, 8, 'Player', 'Seattle', '(298)234-4597', 'Sammy Taylor'),
    (2, 8, 'Player', 'Redmond', '(298)264-4697', 'Lorenzo Donald'),
    (2, 8, 'Player', 'Auburn', '(298)434-4897', 'Fatima Filmore'),
    (2, 8, 'Player', 'Kimberly', '(291)234-4897', 'Aaron Lozenge'),
    (2, 8, 'Player', 'Everett', '(298)234-8794', 'Kevin Table'),
    (2, 8, 'Coach', 'Bellevue', '(298)662-2397', 'Jorge Varmand'),
    (3, 9, 'Player', 'Bellevue', '(298)234-4897', 'Jimmy Taylor'),
    (3, 9, 'Player', 'Redmond', '(298)234-4297', 'Tim Donald'),
    (3, 9, 'Player', 'Auburn', '(298)634-4897', 'Brandon Filmore'),
    (3, 9, 'Player', 'Bellevue', '(292)234-4897', 'Carl Lozenge'),
    (3, 9, 'Player', 'Bellevue', '(298)234-4494', 'Tommy Table'),
    (3, 9, 'Coach', 'Bellevue', '(298)662-4897', 'Jim Varmand'),
    (3, 10, 'Player', 'Bellevue', '(298)234-4897', 'John Taylor'),
    (3, 10, 'Player', 'Redmond', '(298)234-4397', 'Timmy Donald'),
    (3, 10, 'Player', 'Auburn', '(298)634-4897', 'Brandino Filmore'),
    (3, 10, 'Player', 'Bellevue', '(292)334-4897', 'Carlos Lozenge'),
    (3, 10, 'Player', 'Kent', '(298)234-4434', 'Tommy Tom Table'),
    (3, 10, 'Coach', 'Issaquah', '(298)662-4897', 'Jimmy R. Vamanos'),
    (3, 11, 'Player', 'Bellevue', '(298)237-4897', 'Johnny Taylor'),
    (3, 11, 'Player', 'Kirkland', '(298)232-4397', 'Kimmy Donald'),
    (3, 11, 'Player', 'Auburn', '(298)634-5897', 'Trent Filmore'),
    (3, 11, 'Player', 'Bellevue', '(292)233-4897', 'FArla Lozenge'),
    (3, 11, 'Player', 'Tacoma', '(298)234-3494', 'Mickey Table'),
    (3, 11, 'Coach', 'Bellevue', '(298)669-4897', 'Terrell Varmand'),
    (3, 12, 'Player', 'Seattle', '(298)234-4597', 'Sammy Taylor'),
    (3, 12, 'Player', 'Redmond', '(298)264-4697', 'Lorenzo Donald'),
    (3, 12, 'Player', 'Auburn', '(298)434-4897', 'Fatima Filmore'),
    (3, 12, 'Player', 'Kimberly', '(291)234-4897', 'Aaron Lozenge'),
    (3, 12, 'Player', 'Everett', '(298)234-8794', 'Kevin Table'),
    (3, 12, 'Coach', 'Bellevue', '(298)662-2397', 'Jorge Varmand'),
    (4, 13, 'Player', 'Bellevue', '(298)234-4897', 'Jimmy Taylor'),
    (4, 13, 'Player', 'Redmond', '(298)234-4297', 'Tim Donald'),
    (4, 13, 'Player', 'Auburn', '(298)634-4897', 'Brandon Filmore'),
    (4, 13, 'Player', 'Bellevue', '(292)234-4897', 'Carl Lozenge'),
    (4, 13, 'Player', 'Bellevue', '(298)234-4494', 'Tommy Table'),
    (4, 13, 'Coach', 'Bellevue', '(298)662-4897', 'Jim Varmand'),
    (4, 14, 'Player', 'Bellevue', '(298)234-4897', 'John Taylor'),
    (4, 14, 'Player', 'Redmond', '(298)234-4237', 'Timmy Donald'),
    (4, 14, 'Player', 'Auburn', '(298)634-4897', 'Brandino Filmore'),
    (4, 14, 'Player', 'Bellevue', '(292)334-4897', 'Carlos Lozenge'),
    (4, 14, 'Player', 'Kent', '(298)234-4434', 'Tommy Tom Table'),
    (4, 14, 'Coach', 'Issaquah', '(298)662-4897', 'Jimmy R. Vamanos'),
    (4, 15, 'Player', 'Bellevue', '(298)237-4897', 'Johnny Taylor'),
    (4, 15, 'Player', 'Kirkland', '(298)232-4239', 'Kimmy Donald'),
    (4, 15, 'Player', 'Auburn', '(298)634-5897', 'Trent Filmore'),
    (4, 15, 'Player', 'Bellevue', '(292)233-4897', 'FArla Lozenge'),
    (4, 15, 'Player', 'Tacoma', '(298)234-3494', 'Mickey Table'),
    (4, 15, 'Coach', 'Bellevue', '(298)669-4897', 'Terrell Varmand'),
    (4, 16, 'Player', 'Seattle', '(298)234-4597', 'Sammy Taylor'),
    (4, 16, 'Player', 'Redmond', '(298)264-4697', 'Lorenzo Donald'),
    (4, 16, 'Player', 'Auburn', '(298)434-4897', 'Fatima Filmore'),
    (4, 16, 'Player', 'Kimberly', '(291)234-4897', 'Aaron Lozenge'),
    (4, 16, 'Player', 'Everett', '(298)234-8794', 'Kevin Table'),
    (4, 16, 'Coach', 'Bellevue', '(298)662-2397', 'Jorge Varmand');

--
-- Name: games_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.games_id_seq', 192, true);


--
-- Name: knex_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.knex_migrations_id_seq', 1, false);


--
-- Name: knex_migrations_lock_index_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.knex_migrations_lock_index_seq', 1, true);


--
-- Name: leagues_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.leagues_id_seq', 16, true);


--
-- Name: players_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.players_id_seq', 96, true);


--
-- Name: teams_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.teams_id_seq', 16, true);


--
-- Name: games games_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_pkey PRIMARY KEY (id);


--
-- Name: knex_migrations_lock knex_migrations_lock_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.knex_migrations_lock
    ADD CONSTRAINT knex_migrations_lock_pkey PRIMARY KEY (index);


--
-- Name: knex_migrations knex_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.knex_migrations
    ADD CONSTRAINT knex_migrations_pkey PRIMARY KEY (id);


--
-- Name: leagues leagues_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.leagues
    ADD CONSTRAINT leagues_pkey PRIMARY KEY (id);


--
-- Name: players players_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.players
    ADD CONSTRAINT players_pkey PRIMARY KEY (id);


--
-- Name: schemaversion schemaversion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.schemaversion
    ADD CONSTRAINT schemaversion_pkey PRIMARY KEY (version);


--
-- Name: teams teams_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_pkey PRIMARY KEY (id);


--
-- Name: games games_awayteamid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_awayteamid_fkey FOREIGN KEY (awayteamid) REFERENCES public.teams(id) ON DELETE CASCADE;


--
-- Name: games games_hometeamid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_hometeamid_fkey FOREIGN KEY (hometeamid) REFERENCES public.teams(id) ON DELETE CASCADE;


--
-- Name: games games_leagueid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_leagueid_fkey FOREIGN KEY (leagueid) REFERENCES public.leagues(id) ON DELETE CASCADE;


--
-- Name: players players_leagueid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.players
    ADD CONSTRAINT players_leagueid_fkey FOREIGN KEY (leagueid) REFERENCES public.leagues(id) ON DELETE CASCADE;


--
-- Name: players players_teamid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.players
    ADD CONSTRAINT players_teamid_fkey FOREIGN KEY (teamid) REFERENCES public.teams(id) ON DELETE CASCADE;


--
-- Name: teams teams_leagueid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_leagueid_fkey FOREIGN KEY (leagueid) REFERENCES public.leagues(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

